services:
  # Jenkins CI/CD
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    networks:
      - eday-network
  eday-discovery-service:
    build: ./discovery-service
    container_name: eday-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eday-discovery-service:8761/actuator/health" ]
      interval: 10s
      retries: 4
    networks:
      - eday-network


  eday-config-service:
    build: ./config-service
    container_name: eday-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://eday-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eday-config-service:9999/actuator/health" ]
      interval: 15s
      retries: 8
    depends_on:
      eday-discovery-service:
        condition: service_healthy
    networks:
      - eday-network
  eday-customer-service:
    build: ./customer-service
    container_name: eday-customer-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://eday-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://eday-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eday-customer-service:8083/actuator/health" ]
      interval: 15s
      retries: 6
    depends_on:
      eday-config-service:
        condition: service_healthy
    networks:
      - eday-network
  eday-account-service:
    build: ./account-service
    container_name: eday-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://eday-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://eday-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eday-account-service:8082/actuator/health" ]
      interval: 15s
      retries: 8
    depends_on:
      eday-customer-service:
        condition: service_healthy
    networks:
      - eday-network
  eday-gateway-service:
    build: ./gateway-service
    container_name: eday-gateway-service
    ports:
      - '8881:8881'
    expose:
      - '8881'
    environment:
      - DISCOVERY_SERVICE_URL=http://eday-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://eday-config-service:9999
    depends_on:
      eday-account-service:
        condition: service_healthy
    networks:
      - eday-network

networks:
    eday-network:
      driver: bridge

volumes:
  jenkins_home:


