spring:
  cloud:
    gateway:
      routes:
        - id: customerService
          uri: http://localhost:8082/
          predicates:
            - Path=/customers/**
        - id: accountService
          uri: http://localhost:8081/
          predicates:
            - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8888


