apiVersion: v1
kind: Service
metadata:
  name: eday-discovery-service
  namespace: eday
spec:
  selector:
    app: eday-discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
