package com.dreamsoft.kyc.entities.enumerations;

public enum IdRejectedReason {
    BAD_PROOF_OF_IDENTITY,
    EXPIRATION_DATE,
    BAD_SELFIE,
    SELFIE_UNSUPPORTED_FILE_FORMAT,
    SELFIE_FILE_TOO_BIG,
    SELFIE_NOT_HUMAN_PICTURE,
    SELFIE_UNSATISFACTORY_PHOTOS,
    SELFIE_DOCUMENT_DAMAGED,
    RECTO_UNSUPPORTED_FILE_FORMAT,
    RECTO_FILE_TOO_BIG,
    RECTO_NOT_ID_DOCUMENT,
    RECTO_UNSATISFACTORY_PICTURE,
    RECTO_DOCUMENT_DAMAGED,
    VERSO_UNSUPPORTED_FILE_FORMAT,
    VERSO_FILE_TOO_BIG,
    VERSO_NOT_ID_DOCUMENT,
    VERSO_UNSATISFACTORY_PICTURE,
    VERSO_DOCUMENT_DAMAGED,
    OTHERS,
}
