apiVersion: v1
kind: Service
metadata:
  name: eday-account-service
  namespace: eday
spec:
  selector:
    app: eday-account-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
