apiVersion: apps/v1
kind: Deployment
metadata:
  name: eday-config-service
  namespace: eday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eday-config-service
  template:
    metadata:
      labels:
        app: eday-config-service
    spec:
      containers:
        - name: config
          image: yadibrahim/eday-config-service:latest
          ports:
            - containerPort: 9999
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://eday-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 15
            periodSeconds: 10


