apiVersion: v1
kind: Service
metadata:
  name: eday-config-service
  namespace: eday
spec:
  selector:
    app: eday-config-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP
